- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]

# - name: Services are not running
#   service:
#     name: "{{ item }}"
#     state: stopped
#   ignore_errors: yes
#   with_items: "{{ obsolete_services }}"
#   tags: [common]

- name: Facter is present
  apt:
    name: facter
    state: present
  tags: [common]

- name: Execute Facter
  command: facter
  register: result
  tags: [common]

- debug: var=result verbosity=2