---

- name: Clone Steve
  git: 
    repo: https://github.com/gikoluo/Steve.git
    dest: roles/steve/files/steve
    version: master
    recursive: no
    depth: 1
    accept_hostkey: yes
    update: no


- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  tags: [steve]

