base:
  image: 10.100.168.201:5000/web
  ports:
    - 8080
  environment:
    - SERVICE_NAME=web

app:
  extends:
    service: base
  links:
    - db:db
    - cache:cache

db:
  image: mongo

cache:
  image: memcached
