---
- name: Add Ansible repository
  apt_repository: repo='ppa:ansible/ansible'
  tags: [ansbile]

- name: Upgrade Ansible to the lastest
  apt:
    name: ansible
    state: latest
  tags: [ansbile]

- debug: msg="Have to execute this role twice, when ansible is upgrade"

- name: Ansible Galaxies are present
  command: "ansible-galaxy install {{ item }}"
  with_items:
    - AnsibleShipyard.ansible-zookeeper
    - geerlingguy.jenkins
    - archf.nptd
    - pcextreme.supervisor
    - saucelabs-ansible.pip
    - dochang.docker


