- name: Facter is present
  apt:
    name: facter
    force: yes
  tags: [common]

- name: Execute Facter
  command: facter
  tags: [common]

- name: Container is running
  docker:
    name: "{{ registrator_name }}"
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ ansible_hostname }}"
    command: -ip {{ facter_ipaddress_enp0s8 }} {{ registrator_protocol }}://{{ facter_ipaddress_enp0s8 }}:{{ registrator_port }}
  tags: [registrator]
