- name: Container is running2
  docker_container:
    name: "{{ registrator_name }}"
    image: gliderlabs/registrator
    network_mode: host
    state: started
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ ansible_hostname }}"
    command: "{{ registrator_protocol }}://localhost:{{ registrator_port }}/services"
  tags: [registrator]

