- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  tags: [config]

- name: Consul config
  shell: consul-template  -consul alpha-01:8500 \
           -template "/data/nginx/upstreams/pyweb_upstreams.ctmpl:/data/nginx/upstreams/pyweb_upstreams.conf" \
           -once

# - name: nginx service
#   docker:
#     name: nginx
#     image: "{{ docker_nginx_image }}"
#     state: reloaded