- name: Debian, use a quickly source, 163 mirror.
  replace: 
    dest: /etc/apt/sources.list
    regexp: "archive.ubuntu.com"
    replace: "{{ source_list }}"
    backup: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'Download Accelerate Docker mirror'
  get_url: url='https://get.daocloud.io/daotools/set_mirror.sh' dest='/var/set_mirror.sh' mode='0755'
  register: result

- name: 'Execute Accelerate Docker mirror'
  command: /var/set_mirror.sh  -s http://99c6e2d5.m.daocloud.io
  when: result.changed

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: result.changed
  tags: [docker]


# - name: Setup zsh
#   apt: 
#     name: zsh
#     state: latest
#     force: yes

# - name: setup ohmyzsh
#   get_url: url='https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh' dest='/var/oh-my-zsh-install.sh'
#   register: myzsh_result

# - name: excute my
#   command: "sh /var/oh-my-zsh-install.sh"
#   when: myzsh_result.changed
