# - name: Debian add Docker repository and update apt cache
#   apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main'
#   tags: [docker]

# - name: Debian Docker is present
#   apt:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - curl
#     - docker-engine
#     - python-pip
#   tags: [docker]

# - name: Debian upgrade pip package
#   pip:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - pip
#     - httplib2
#   tags: [docker]

# - name: Debian docker-py is present
#   pip: name=docker-py
#   tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_result
  notify: restart docker
  tags: [docker]

- name: Dock Config2
  lineinfile: 
    dest: "/lib/systemd/system/docker.service"
    state: "present"
    regexp: "^ExecStart=/usr/bin/dockerd"
    line: "ExecStart=/usr/bin/dockerd --config-file=/etc/docker/daemon.json"
  when: copy_result|changed and ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify: restart docker
  tags: [docker]

- systemd: state=restarted daemon_reload=yes name=docker

# - name: ubuntu user is added to the docker group
#   user:
#     name: ubuntu
#     group: docker
#   notify: restart docker
#   tags: [docker]

# - name: vagrant user is added to the docker group
#   user:
#     name: vagrant
#     group: docker
#   notify: restart docker
#   tags: [docker]

- include: roles/docker/tasks/dockerui.yml

