- hosts: localhost
  remote_user: ubuntu
  become: True
  become_user: root
  roles:
    - cn
    - base
    - update
    - role: pcextreme.supervisor
    - steve
    - role: saucelabs-ansible.pip
    - role: dochang.docker
    - role: docker

  handlers:
    - include: handlers/all.yml
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes
