- hosts: localhost
  remote_user: ubuntu
  serial: 1
  become: True
  become_user: root
  roles:
    - cn
    - update
    - ansible
    - dev
    - common
    - confd
    - docker
    - consul
    - consul-template