- hosts: zookeepers
  remote_user: ubuntu
  become: True
  become_user: root
  roles:
    - common
    - docker
    - docker-compose
    - role: "AnsibleShipyard.ansible-zookeeper"
      zookeeper_hosts: "{{groups['zookeepers']}}"
      