- name: Setup git-core
  apt:
    name: git-core
    state: latest
    force: yes
    
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Setup locale
  apt:
    name: language-pack-zh-hans
    state: latest
    force: yes
  tags: [docker]

- name: setup locale 2
  apt:
    name: language-pack-en
    state: latest
    force: yes
  tags: [docker]